### PR TITLE
INFRA01 - Create a check for a11y

### LINKED ISSUE #94: INFRA01 - Create a check for a11y
The reference for the check is [here](https://bolonio.medium.com/automating-the-accessibility-tests-of-your-source-code-with-github-actions-63590cdc6860). 

The check should run on every PR opened to main, but can be tested on a separate branch before we merge it on main.

### PR DESCRIPTION
**Pull request by gregoriopalama**
closes #94

### CODE REVIEW

**Comment by gregoriopalama** [comment]
This will also
close #95

**Comment by irsooti** [comment]
LGTM!

Just curious: you are using pnpm caching in a different and longer way than I did in #96, do you see any issues about that? 

See the lines: https://github.com/gdgpescara/hedwig/pull/99/files#diff-7afcd2d8f7b49bda74843f209eefb7b2da45f7e7803bf2e4bd636699b76aa2d3R12-R19 .

**Comment by gregoriopalama** [comment]
Nope, I'm using the default retention, should be fine.
Also, a lot of nice things are still not supported in pnpm and there are open PRs right now. 

We should monitor this: https://github.com/pnpm/action-setup/issues/99
And update our workflows as soon as this get merged

**Comment by irsooti** [comment]
oof

**Pull request merged**
